# You are given two strings s and t. 
# 
#  String t is generated by random shuffling string s and then add one more 
# letter at a random position. 
# 
#  Return the letter that was added to t. 
# 
#  
#  Example 1: 
# 
#  
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#  
# 
#  Example 2: 
# 
#  
# Input: s = "", t = "y"
# Output: "y"
#  
# 
#  
#  Constraints: 
# 
#  
#  0 <= s.length <= 1000 
#  t.length == s.length + 1 
#  s and t consist of lowercase English letters. 
#  
# 
#  Related Topics Hash Table String Bit Manipulation Sorting 👍 5145 👎 493


# leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    ### 1. XOR Approach
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0
        # XOR every character in s
        for ch in s:
            result ^= ord(ch)
        # XOR every character in t
        for ch in t:
            result ^= ord(ch)
        # The result is the extra letter's ASCII value
        return chr(result)

    ### 2. Frequency Dictionary Approach
    # def findTheDifference(self, s: str, t: str) -> str:
    #     s_dict = {}
    #     for i in s:
    #         if i in s_dict:
    #             s_dict[i] += 1
    #         else:
    #             s_dict[i] = 1
    #
    #     for j in t:
    #         if j in s_dict and s_dict[j] > 0:
    #             s_dict[j] -= 1
    #         else:
    #             return j
# leetcode submit region end(Prohibit modification and deletion)
